apiVersion: apps/v1
kind: Deployment
metadata:
  name: Backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Backend-app
  template:
    metadata:
      labels:
        app: Backend-app
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: Backend-app
        image: ghcr.io/ismail-bradai/hello-world-velodoc:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: Backend-app
  namespace: default
spec:
  selector:
    app: Backend-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
